### ISSUE TITLE
Does not seem to work for "plural "types

### ISSUE THREAD

**Issue by peaceful-james** [curiosum-dev/kanta_po_writer_plugin#2]
This plugin works great for "singular" types.

However, plural types (when there are 2 forms) are not written to the po file.

I have uploaded some screenshots which should make the issue clear.

![image](https://github.com/curiosum-dev/kanta_po_writer_plugin/assets/66864163/1426c15f-97d2-4457-9957-090a155e0561)

![image](https://github.com/curiosum-dev/kanta_po_writer_plugin/assets/66864163/94343217-d7ca-4317-88ca-5c019cfb7745)

![image](https://github.com/curiosum-dev/kanta_po_writer_plugin/assets/66864163/96053048-4125-41f3-a33a-aff0285af9b4)

**Comment by ravensiris** [comment]
This is a very much a TODO.
https://github.com/curiosum-dev/kanta_po_writer_plugin/blob/main/lib/extractor.ex#L77-L78

**Comment by peaceful-james** [comment]
I think #4 fixes this
